"use client";
import {useEffect,useState} from "react";
import "./billing-controls.css";
import {networkError} from "../request-errors";

const API=process.env.NEXT_PUBLIC_API_URL||"https://api.feather-map.com";
async function call(path:string,token:string,options:RequestInit={}){let response:Response;try{response=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...options.headers}})}catch(cause){throw networkError("admin",cause)}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Billing request failed (${response.status})`);return data}
const money=(amount:number,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency:(currency||"usd").toUpperCase()}).format((amount||0)/100);

export default function BillingControls({visible,token}:{visible:boolean;token:string}){
 const[data,setData]=useState<any>(null),[catalog,setCatalog]=useState<any[]>([]),[status,setStatus]=useState("");
 async function load(){if(!visible||!token)return;setStatus("Loading billing configuration…");try{setData(await call("/api/admin/billing",token));setStatus("")}catch(error){setStatus(error instanceof Error?error.message:"Could not load billing configuration")}}
 useEffect(()=>{void load()},[visible,token]);
 async function saveConfig(){setStatus("Saving subscription behavior…");try{await call("/api/admin/billing/config",token,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data.config)});await load();setStatus("Subscription behavior saved")}catch(error){setStatus(error instanceof Error?error.message:"Could not save subscription behavior")}}
 async function testConnection(){setStatus("Testing Stripe connection…");try{await call("/api/admin/billing/test-connection",token,{method:"POST"});await load();setStatus("Stripe connection verified")}catch(error){setStatus(error instanceof Error?error.message:"Stripe connection failed")}}
 async function loadCatalog(){setStatus("Loading Stripe prices…");try{const result=await call("/api/admin/billing/catalog",token);setCatalog(result.prices||[]);setStatus("")}catch(error){setStatus(error instanceof Error?error.message:"Could not load Stripe prices")}}
 async function mapPrice(level:string,priceId:string){if(!priceId)return;setStatus("Saving Stripe price mapping…");try{await call(`/api/admin/billing/tiers/${level}/prices`,token,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider_price_id:priceId})});await load();setStatus("Stripe price mapped")}catch(error){setStatus(error instanceof Error?error.message:"Could not map Stripe price")}}
 if(!visible)return null;if(!data)return <section className="billing-controls"><div className="admin-notice">{status||"Loading billing…"}</div></section>;
 const setConfig=(key:string,value:unknown)=>setData((current:any)=>({...current,config:{...current.config,[key]:value}}));
 return <section className="billing-controls">
  <header><div><h2>Billing</h2><p>Stripe account health, subscription tiers, entitlement policy, and synchronization.</p></div><button onClick={load}>Refresh</button></header>
  {status&&<div className="admin-notice" role="status">{status}</div>}
  <section className="billing-section"><div className="billing-heading"><div><h3>Stripe account</h3><p>Credentials are deployment secrets and are never displayed here.</p></div><span className={`billing-state ${data.state.configured?"ready":"warning"}`}>{data.state.configured?(data.state.livemode?"Live mode":"Test mode"):"Not configured"}</span></div>
   <div className="billing-account"><dl><div><dt>Account</dt><dd>{data.account?.business_name||data.account?.id||"Unavailable"}</dd></div><div><dt>Charges</dt><dd>{data.account?.charges_enabled?"Enabled":"Unavailable"}</dd></div><div><dt>Payouts</dt><dd>{data.account?.payouts_enabled?"Enabled":"Unavailable"}</dd></div><div><dt>Webhook signing</dt><dd>{data.state.webhook_configured?"Configured":"Missing"}</dd></div></dl>{data.connection_error&&<div className="billing-error">{data.connection_error}</div>}<button className="primary" disabled={!data.state.configured} onClick={testConnection}>Test connection</button></div>
  </section>
  <section className="billing-section"><div className="billing-heading"><div><h3>Billing tiers</h3><p>Map active recurring Stripe prices to FeatherMap membership levels.</p></div><button onClick={loadCatalog}>Load Stripe catalog</button></div>
   <div className="billing-tier-grid">{data.levels.map((level:any)=><article key={level.key}><div><h4>{level.display_name}</h4><code>{level.key}</code><p>{level.description}</p></div><div className="mapped-prices">{data.prices.filter((price:any)=>price.level_key===level.key).map((price:any)=><span key={price.id}><b>{price.billing_interval}</b>{money(price.unit_amount,price.currency)} <small>{price.provider_price_id}</small></span>)}</div>{catalog.length>0&&<label>Stripe price<select defaultValue="" onChange={event=>mapPrice(level.key,event.target.value)}><option value="">Choose a recurring price…</option>{catalog.map(price=><option value={price.price_id} key={price.price_id}>{price.product_name} · {money(price.unit_amount,price.currency)}/{price.interval}</option>)}</select></label>}</article>)}</div>
  </section>
  <section className="billing-section"><div className="billing-heading"><div><h3>Subscription behavior</h3><p>Controls checkout and the entitlement policy shared by web, iOS, and Android.</p></div></div>
   <div className="billing-config-grid">{[["enabled","Billing enabled"],["checkout_enabled","New checkout enabled"],["monthly_enabled","Monthly plans"],["annual_enabled","Annual plans"],["automatic_tax","Automatic tax"],["promotion_codes","Promotion codes"],["trialing_grants_access","Trialing grants access"],["past_due_grants_access","Past due grace access"],["cancel_access_at_period_end","Access through canceled period"]].map(([key,label])=><label className="billing-toggle" key={key}><span>{label}</span><input type="checkbox" checked={data.config[key]===true} onChange={event=>setConfig(key,event.target.checked)}/></label>)}<label>Trial days<input type="number" min="0" max="365" value={data.config.trial_days||0} onChange={event=>setConfig("trial_days",Number(event.target.value))}/></label><label>Past-due grace days<input type="number" min="0" max="365" value={data.config.past_due_grace_days||0} onChange={event=>setConfig("past_due_grace_days",Number(event.target.value))}/></label><label>Default free tier<input value={data.config.default_free_tier||"free"} onChange={event=>setConfig("default_free_tier",event.target.value)}/></label><label>Billing support email<input type="email" value={data.config.billing_support_email||""} onChange={event=>setConfig("billing_support_email",event.target.value)}/></label><label>Terms URL<input type="url" value={data.config.terms_url||""} onChange={event=>setConfig("terms_url",event.target.value)}/></label><label>Refund policy URL<input type="url" value={data.config.refund_policy_url||""} onChange={event=>setConfig("refund_policy_url",event.target.value)}/></label></div><button className="primary" onClick={saveConfig}>Save subscription behavior</button>
  </section>
  <section className="billing-section"><div className="billing-heading"><div><h3>Billing health</h3><p>Recent subscription totals, webhook processing, and synchronization results.</p></div></div><div className="billing-metrics">{Object.entries(data.health.subscriptions||{}).map(([key,value])=><div key={key}><b>{String(value)}</b><span>{key.replaceAll("_"," ")}</span></div>)}</div><div className="billing-events">{data.health.recent_events?.length?data.health.recent_events.map((event:any)=><p key={event.event_id}><b>{event.event_type}</b><span className={event.processing_status}>{event.processing_status}</span><small>{new Date(event.received_at).toLocaleString()}</small></p>):<p>No Stripe webhook events received yet.</p>}</div></section>
 </section>
}
