"use client";
import {FormEvent,useState} from "react";
import "./count-range-setup.css";

type CountRange={slug:string;display_label:string;minimum_count:number;maximum_count:number|null;description?:string|null;sort_order:number;enabled:boolean;archived_at?:string|null};
const empty={display_label:"",minimum_count:1,maximum_count:10,description:"",sort_order:100,enabled:true};
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");

export default function CountRangeSetup({ranges,canManage,onSave}:{ranges:CountRange[];canManage:boolean;onSave:(path:string,payload:unknown,method?:string)=>Promise<void>}){
 const[draft,setDraft]=useState<any>(empty),[editing,setEditing]=useState<CountRange|null>(null);
 async function create(event:FormEvent){event.preventDefault();await onSave("/api/admin/count-ranges",{...draft,slug:slugify(draft.display_label)},"POST");setDraft(empty)}
 return <section className="catalog-section count-range-setup"><div className="catalog-section-heading"><div><h3>Report count ranges</h3><p>Global choices for estimating birds observed. Historical reports keep their original range.</p></div><span>{ranges.filter(item=>item.enabled&&!item.archived_at).length} active</span></div>
 {canManage&&<form className="count-range-form" onSubmit={create}><label>Label<input required maxLength={40} value={draft.display_label} onChange={event=>setDraft({...draft,display_label:event.target.value})} placeholder="e.g. 100,000+"/></label><label>Minimum<input required type="number" min="1" value={draft.minimum_count} onChange={event=>setDraft({...draft,minimum_count:Number(event.target.value)})}/></label><label>Maximum<input type="number" min={draft.minimum_count} value={draft.maximum_count??""} onChange={event=>setDraft({...draft,maximum_count:event.target.value===""?null:Number(event.target.value)})} placeholder="No maximum"/></label><label>Order<input required type="number" value={draft.sort_order} onChange={event=>setDraft({...draft,sort_order:Number(event.target.value)})}/></label><label className="wide">Description<input maxLength={240} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><button className="primary">Add range</button></form>}
 <div className="count-range-list">{ranges.map(item=><article key={item.slug} className={!item.enabled||item.archived_at?"inactive":""}><span><b>{item.display_label}</b><small>{Number(item.minimum_count).toLocaleString()}–{item.maximum_count===null?"unlimited":Number(item.maximum_count).toLocaleString()} · order {item.sort_order}</small>{item.description&&<small>{item.description}</small>}</span>{canManage&&<button onClick={()=>setEditing({...item})}>Edit</button>}</article>)}</div>
 {editing&&<div className="admin-overlay" onClick={()=>setEditing(null)}><section className="admin-detail catalog-editor" onClick={event=>event.stopPropagation()}><button className="detail-close" aria-label="Close count range editor" onClick={()=>setEditing(null)}>×</button><h2>Edit report count range</h2><div className="detail-form"><label>Label<input value={editing.display_label} onChange={event=>setEditing({...editing,display_label:event.target.value})}/></label><label>Minimum<input type="number" min="1" value={editing.minimum_count} onChange={event=>setEditing({...editing,minimum_count:Number(event.target.value)})}/></label><label>Maximum<input type="number" min={editing.minimum_count} value={editing.maximum_count??""} onChange={event=>setEditing({...editing,maximum_count:event.target.value===""?null:Number(event.target.value)})} placeholder="No maximum"/></label><label>Order<input type="number" value={editing.sort_order} onChange={event=>setEditing({...editing,sort_order:Number(event.target.value)})}/></label><label>Description<input value={editing.description||""} onChange={event=>setEditing({...editing,description:event.target.value})}/></label><label className="catalog-toggle"><input type="checkbox" checked={editing.enabled&&!editing.archived_at} onChange={event=>setEditing({...editing,enabled:event.target.checked,archived_at:event.target.checked?null:new Date().toISOString()})}/> Active and reportable</label></div><button className="primary" onClick={async()=>{await onSave(`/api/admin/count-ranges/${editing.slug}`,{...editing,archived:Boolean(editing.archived_at)});setEditing(null)}}>Save range</button></section></div>}
 </section>
}
