import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

test("keeps report choices visible and scales bird-weighted density to local zoom",async()=>{const[page,theme,mapCss,api]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/theme.css",import.meta.url),"utf8"),readFile(new URL("../app/map-radar.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8")]);assert.match(theme,/choice-grid button\.active/);assert.match(theme,/content:"✓"/);assert.match(page,/setSpecies\(current=>next\.some/);assert.match(page,/zoom>=7&&zoom<12/);assert.match(page,/protected-report-dots/);assert.match(page,/zoom>=12&&visibleReports/);assert.match(page,/--bird-volume/);assert.match(mapCss,/\.map-cluster,\.hotspot\{display:none!important\}/);assert.match(mapCss,/clamp\(10px/);assert.match(mapCss,/width:28px/);assert.ok(api.includes("zoom<12?.06:.03"));assert.match(api,/local_marker_zoom/)});

test("ships synchronized themes, catalog setup, and readable activity",async()=>{const[theme,adminCss,admin,catalog,api,migration]=await Promise.all([readFile(new URL("../app/theme.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-directory.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/catalog-setup.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_category_catalog_setup.sql",import.meta.url),"utf8")]);assert.match(theme,/One theme surface model/);assert.match(theme,/transition:none!important/);assert.match(admin,/CatalogSetup/);assert.match(catalog,/Bird categories/);assert.match(catalog,/Edit category/);assert.match(adminCss,/activity-filters>.primary/);assert.match(api,/activityLabels/);assert.match(api,/deviceLabel/);assert.ok(api.includes("/api/admin/categories"));assert.match(api,/Deleted activity report/);assert.match(migration,/add column if not exists color/);assert.match(migration,/add column if not exists icon/)});

test("keeps successful admin responses CORS-safe and scales national aggregation",async()=>{const[page,css,api,layout,icon]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/map-radar.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/layout.tsx",import.meta.url),"utf8"),readFile(new URL("../public/favicon.svg",import.meta.url),"utf8")]);assert.match(api,/deleted_reports:[\s\S]*\}\},origin\)/);assert.match(api,/"Cache-Control": "no-store"/);assert.match(api,/adaptiveGrid/);assert.match(page,/useState\(180\)/);assert.match(page,/heatmap\?\$\{rangeQuery\(\)\}&zoom=/);assert.match(css,/density-dot::before/);assert.match(layout,/favicon\.svg/);assert.match(icon,/bdf437/)});

async function render(path="/"){
  const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}`);const{default:worker}=await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${path}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}});
}

test("server-renders the FeatherMap map",async()=>{const response=await render();assert.equal(response.status,200);const html=await response.text();assert.match(html,/<title>FeatherMap/);assert.match(html,/MIGRATORY ACTIVITY, EXACT LOCATIONS PROTECTED/);assert.match(html,/Past 7 days/);assert.match(html,/Report birds/);assert.doesNotMatch(html,/codex-preview|Your site is taking shape/)});

test("ships protected administration and trust features",async()=>{for(const path of ["/admin","/auth/reset-password"]){const response=await render(path);assert.equal(response.status,200)}const[api,migration]=await Promise.all([readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_trust_layers_profile.sql",import.meta.url),"utf8")]);assert.match(api,/\/api\/auth\/recover/);assert.match(api,/\/api\/admin\/duplicates/);assert.match(api,/weatherSnapshot/);assert.match(api,/scrubImage/);assert.match(api,/signout-all/);assert.match(migration,/duplicate_candidates/);assert.match(migration,/hunting_regulations/);assert.match(migration,/notifications/)});

test("keeps map overlays legible in light and system themes",async()=>{const css=await readFile(new URL("../app/theme.css",import.meta.url),"utf8");assert.match(css,/\.filter:not\(\.active\)/);assert.match(css,/\.filter\.active\{background:#f4f7f2;color:#142019/);assert.match(css,/\.hotspot span\{color:#fff\}/);assert.match(css,/\.map-attribution/);assert.match(css,/\.heat-legend/)});

test("ships the privacy-safe density map and owner report deletion",async()=>{const[page,css,api,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/map-radar.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_owner_report_deletion.sql",import.meta.url),"utf8")]);assert.match(page,/view-density/);assert.match(page,/privacy-safe aggregate cells/);assert.match(page,/Delete my report/);assert.doesNotMatch(page,/Default map visualization/);assert.match(css,/\.density-dot/);assert.match(css,/\.timeframe-control/);assert.match(api,/sighting\.delete/);assert.match(api,/\/restore/);assert.match(migration,/deleted_at/);assert.match(migration,/deleted_by/)});

test("ships configurable migration profiles, directional overlays, and the 100k seed",async()=>{const[overlay,catalog,api,migration,seed]=await Promise.all([readFile(new URL("../app/migration-overlay.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/catalog-setup.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_species_migration_profiles.sql",import.meta.url),"utf8"),readFile(new URL("../supabase/seed_100k_migration_reports.sql",import.meta.url),"utf8")]);assert.match(overlay,/Generalized seasonal direction/);assert.match(overlay,/migration-arrow/);assert.match(catalog,/Typical flock midpoint/);assert.match(catalog,/Migration flyways/);assert.match(api,/migration_profile/);assert.match(migration,/estimated_birds/);assert.match(migration,/typical_flock_median/);assert.match(seed,/generate_series\(1,100000\)/);assert.match(seed,/seed_batch_id/)});

test("supports protected custom and delayed report locations",async()=>{const[page,css,api,admin,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/content-tools.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_custom_report_location_time.sql",import.meta.url),"utf8")]);assert.match(page,/Observation details/);assert.match(page,/Choose on map/);assert.match(page,/Use selected point/);assert.match(page,/Saved or popular area/);assert.match(page,/Search for a place/);assert.match(page,/occurred_at:new Date\(observedAt\)/);assert.match(css,/\.report-context-panel/);assert.match(api,/maxAgeDays=7/);assert.match(api,/Observation time cannot be in the future/);assert.match(api,/locations\/search/);assert.match(api,/submission_context/);assert.match(admin,/max_report_age_days/);assert.match(migration,/location_source/);assert.match(migration,/submitted_at/)});

test("ships actionable administration and readable audit details",async()=>{const[admin,css,api]=await Promise.all([readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-directory.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8")]);assert.match(admin,/Needs attention/);assert.match(admin,/Technical details/);assert.match(admin,/deviceSummary/);assert.match(css,/Original submission · read only/);assert.match(css,/\.operations-overview/);assert.match(api,/action_label/);assert.match(api,/deleted_reports/)});

test("ships responsive administration and complete predefined access roles",async()=>{const[admin,responsive,platform,api,migration,compose]=await Promise.all([readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-responsive.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/platform-controls.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_platform_foundation.sql",import.meta.url),"utf8"),readFile(new URL("../docker-compose.api.yml",import.meta.url),"utf8")]);assert.match(admin,/Manage access/);assert.equal(admin.includes("onChange={e=>action(`/api/admin/users/${u.id}`,{role"),false);assert.match(responsive,/role-choice-grid/);assert.match(responsive,/@media\(max-width:620px\)/);assert.match(platform,/Promise\.allSettled/);assert.match(api,/effective_permissions/);assert.match(migration,/legacy_admin\.promote/);assert.match(migration,/grant select,insert,update,delete/);assert.match(compose,/supabase_internal/)});
