import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

test("ships globally configurable report count ranges with immutable snapshots",async()=>{const[page,api,admin,migration,css]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/admin/count-range-setup.tsx",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_global_count_ranges.sql",import.meta.url),"utf8"),readFile(new URL("../app/queued-iteration.css",import.meta.url),"utf8")]);assert.match(page,/countRanges\.length<=8/);assert.match(page,/Number of birds observed/);assert.match(page,/pendingReportCountRange/);assert.match(api,/\/api\/admin\/count-ranges/);assert.match(api,/flock_label_snapshot/);assert.match(api,/estimated_birds_snapshot/);assert.match(admin,/Report count ranges/);assert.match(admin,/Historical reports keep their original range/);assert.match(migration,/prevent_overlapping_report_count_ranges/);assert.match(migration,/100,000\+/);assert.match(migration,/coalesce\(s\.estimated_birds_snapshot/);assert.match(css,/report-count-buttons/);});

test("ships hierarchical taxonomy, private harvest tracking, and queued map safeguards",async()=>{const[page,api,catalog,css,theme,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/admin/catalog-setup.tsx",import.meta.url),"utf8"),readFile(new URL("../app/queued-iteration.css",import.meta.url),"utf8"),readFile(new URL("../app/theme.css",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_taxonomy_harvest.sql",import.meta.url),"utf8")]);assert.match(page,/deleteReportTarget/);assert.match(page,/owner-status/);assert.match(page,/Harvest journal/);assert.match(page,/taxonFilters/);assert.match(page,/validDays\.includes/);assert.match(api,/\/api\/harvests/);assert.match(api,/\/api\/admin\/subspecies/);assert.match(catalog,/Subspecies and populations/);assert.match(catalog,/Save subtype/);assert.match(css,/:has\(\.report-card\) \.heat-legend/);assert.match(theme,/--surface-header/);assert.match(migration,/create table if not exists public\.subspecies_catalog/);assert.match(migration,/create table if not exists public\.hunting_outings/);assert.match(migration,/create table if not exists public\.harvest_items/);});

test("keeps API hosts environment-driven and rejects retired domains",async()=>{const files=await Promise.all(["../app/page.tsx","../app/admin/page.tsx","../app/appearance-control.tsx","../app/auth/reset-password/page.tsx","../docker-compose.web.yml"].map(path=>readFile(new URL(path,import.meta.url),"utf8")));for(const source of files)assert.doesNotMatch(source,/flyway-api\.zileslabs\.com/);assert.match(files.at(-1),/NEXT_PUBLIC_API_URL: \$\{NEXT_PUBLIC_API_URL:-https:\/\/api\.feather-map\.com\}/)});

test("covers session revocation, warning UI, role details, and category map metadata",async()=>{const[api,page,platform,migration]=await Promise.all([readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/platform-controls.tsx",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_session_map_catalog_iteration.sql",import.meta.url),"utf8")]);assert.match(api,/parseResponseBody/);assert.match(api,/ledger_revoked/);assert.match(api,/touchSession/);assert.match(page,/session-expiry-modal/);assert.match(platform,/role-permission-detail/);assert.match(migration,/category_breakdown jsonb/);assert.match(migration,/reference_url text/)});

test("keeps report choices visible and scales bird-weighted density to local zoom",async()=>{const[page,theme,mapCss,api]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/theme.css",import.meta.url),"utf8"),readFile(new URL("../app/map-radar.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8")]);assert.match(theme,/choice-grid button\.active/);assert.match(theme,/content:"✓"/);assert.match(page,/setSpecies\(current=>next\.some/);assert.match(page,/zoom>=7&&zoom<12/);assert.match(page,/protected-report-dots/);assert.match(page,/zoom>=12&&visibleReports/);assert.match(page,/--bird-volume/);assert.match(mapCss,/\.map-cluster,\.hotspot\{display:none!important\}/);assert.match(mapCss,/clamp\(10px/);assert.match(mapCss,/width:28px/);assert.ok(api.includes("zoom<12?.06:.03"));assert.match(api,/local_marker_zoom/)});

test("ships synchronized themes, catalog setup, and readable activity",async()=>{const[theme,adminCss,admin,catalog,api,migration]=await Promise.all([readFile(new URL("../app/theme.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-directory.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/catalog-setup.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_category_catalog_setup.sql",import.meta.url),"utf8")]);assert.match(theme,/One theme surface model/);assert.match(theme,/transition:none!important/);assert.match(admin,/CatalogSetup/);assert.match(catalog,/Bird categories/);assert.match(catalog,/Edit category/);assert.match(adminCss,/activity-filters>.primary/);assert.match(api,/activityLabels/);assert.match(api,/deviceLabel/);assert.ok(api.includes("/api/admin/categories"));assert.match(api,/Deleted activity report/);assert.match(migration,/add column if not exists color/);assert.match(migration,/add column if not exists icon/)});

test("keeps successful admin responses CORS-safe and scales national aggregation",async()=>{const[page,css,api,layout,icon]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/map-radar.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/layout.tsx",import.meta.url),"utf8"),readFile(new URL("../public/favicon.svg",import.meta.url),"utf8")]);assert.match(api,/deleted_reports:[\s\S]*\}\},origin\)/);assert.match(api,/"Cache-Control": "no-store"/);assert.match(api,/adaptiveGrid/);assert.match(page,/useState\(30\)/);assert.match(page,/heatmap\?\$\{rangeQuery\(\)\}&zoom=/);assert.match(css,/density-dot::before/);assert.match(layout,/favicon\.svg/);assert.match(icon,/bdf437/)});

async function render(path="/"){
  const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}`);const{default:worker}=await import(workerUrl.href);
  return worker.fetch(new Request(`http://localhost${path}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}});
}

test("server-renders the FeatherMap map",async()=>{const response=await render();assert.equal(response.status,200);const html=await response.text();assert.match(html,/<title>FeatherMap/);assert.match(html,/MIGRATORY ACTIVITY, EXACT LOCATIONS PROTECTED/);assert.match(html,/Past 7 days/);assert.match(html,/Report birds/);assert.doesNotMatch(html,/codex-preview|Your site is taking shape/)});

test("ships protected administration and trust features",async()=>{for(const path of ["/admin","/auth/reset-password"]){const response=await render(path);assert.equal(response.status,200)}const[api,migration]=await Promise.all([readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_trust_layers_profile.sql",import.meta.url),"utf8")]);assert.match(api,/\/api\/auth\/recover/);assert.match(api,/\/api\/admin\/duplicates/);assert.match(api,/weatherSnapshot/);assert.match(api,/scrubImage/);assert.match(api,/signout-all/);assert.match(migration,/duplicate_candidates/);assert.match(migration,/hunting_regulations/);assert.match(migration,/notifications/)});
test("ships guarded self-service account deletion",async()=>{const[page,api,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_account_deletion.sql",import.meta.url),"utf8")]);assert.match(page,/Permanently delete account/);assert.match(page,/confirmation:deleteConfirmation/);assert.match(api,/\/api\/account\/delete/);assert.match(api,/prepare_account_deletion/);assert.match(api,/assertSuperAdminContinuity\(user\.id/);assert.match(migration,/security definer/);assert.match(migration,/admin_audit_log set actor_id = null/)});
test("keeps close controls visible in light and system themes",async()=>{const css=await readFile(new URL("../app/queued-iteration.css",import.meta.url),"utf8");assert.match(css,/data-theme="light"[^\n]+modal-head>button[^\n]+color:#f7faf5!important/);assert.match(css,/prefers-color-scheme:light[^\n]+data-theme="system"[^\n]+panel-close/);assert.match(css,/focus-visible[^\n]+outline-offset:2px/)});

test("keeps map overlays legible in light and system themes",async()=>{const css=await readFile(new URL("../app/theme.css",import.meta.url),"utf8");assert.match(css,/\.filter:not\(\.active\)/);assert.match(css,/\.filter\.active\{background:#f4f7f2;color:#142019/);assert.match(css,/\.hotspot span\{color:#fff\}/);assert.match(css,/\.map-attribution/);assert.match(css,/\.heat-legend/)});

test("ships the privacy-safe density map and owner report deletion",async()=>{const[page,css,api,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/map-radar.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_owner_report_deletion.sql",import.meta.url),"utf8")]);assert.match(page,/view-density/);assert.match(page,/privacy-safe aggregate cells/);assert.match(page,/Delete my report/);assert.doesNotMatch(page,/Default map visualization/);assert.match(css,/\.density-dot/);assert.match(css,/\.timeframe-control/);assert.match(api,/sighting\.delete/);assert.match(api,/\/restore/);assert.match(migration,/deleted_at/);assert.match(migration,/deleted_by/)});

test("ships configurable migration profiles, directional overlays, and the 100k seed",async()=>{const[overlay,catalog,api,migration,seed]=await Promise.all([readFile(new URL("../app/migration-overlay.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/catalog-setup.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_species_migration_profiles.sql",import.meta.url),"utf8"),readFile(new URL("../supabase/seed_100k_migration_reports.sql",import.meta.url),"utf8")]);assert.match(overlay,/Generalized seasonal direction/);assert.match(overlay,/migration-arrow/);assert.match(catalog,/Typical flock midpoint/);assert.match(catalog,/Migration flyways/);assert.match(api,/migration_profile/);assert.match(migration,/estimated_birds/);assert.match(migration,/typical_flock_median/);assert.match(seed,/generate_series\(1,100000\)/);assert.match(seed,/seed_batch_id/)});

test("supports protected custom and delayed report locations",async()=>{const[page,css,api,admin,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/content-tools.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_custom_report_location_time.sql",import.meta.url),"utf8")]);assert.match(page,/Observation details/);assert.match(page,/Choose on map/);assert.match(page,/Use selected point/);assert.match(page,/Saved or popular area/);assert.match(page,/Search for a place/);assert.match(page,/occurred_at:new Date\(observedAt\)/);assert.match(css,/\.report-context-panel/);assert.match(api,/maxAgeDays=7/);assert.match(api,/Observation time cannot be in the future/);assert.match(api,/locations\/search/);assert.match(api,/submission_context/);assert.match(admin,/max_report_age_days/);assert.match(migration,/location_source/);assert.match(migration,/submitted_at/)});

test("ships actionable administration and readable audit details",async()=>{const[admin,css,api]=await Promise.all([readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-directory.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8")]);assert.match(admin,/Needs attention/);assert.match(admin,/Technical details/);assert.match(admin,/deviceSummary/);assert.match(css,/Original submission · read only/);assert.match(css,/\.operations-overview/);assert.match(api,/action_label/);assert.match(api,/deleted_reports/)});

test("ships responsive administration and complete predefined access roles",async()=>{const[admin,responsive,platformCss,platform,api,migration,compose]=await Promise.all([readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-responsive.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/platform-controls.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/platform-controls.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_platform_foundation.sql",import.meta.url),"utf8"),readFile(new URL("../docker-compose.api.yml",import.meta.url),"utf8")]);assert.match(admin,/Manage access/);assert.match(admin,/audit-columns/);assert.match(admin,/Saving access/);assert.match(admin,/Catalog Setup/);assert.match(admin,/mfa-policy-summary/);assert.equal(admin.includes("Require administrator TOTP"),false);assert.ok(admin.indexOf("<PlatformControls")<admin.indexOf("\n {selectedCase"));assert.equal(admin.includes("onChange={e=>action(`/api/admin/users/${u.id}`,{role"),false);assert.match(responsive,/role-choice-grid/);assert.match(responsive,/audit-card/);assert.match(responsive,/access-save/);assert.match(platformCss,/@container/);assert.match(platform,/Promise\.allSettled/);assert.match(api,/GET, POST, PUT, PATCH/);assert.match(api,/effective_permissions/);assert.match(migration,/legacy_admin\.promote/);assert.match(migration,/grant select,insert,update,delete/);assert.match(compose,/supabase_internal/)});
test("shows active roles, location progress, consistent platform actions, and policy-aware MFA",async()=>{const[page,admin,responsive,platformCss,api]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-responsive.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/platform-controls.css",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8")]);assert.match(page,/Finding your location/);assert.match(page,/map-location-status/);assert.match(page,/Location permission denied/);assert.match(admin,/user-role-badges/);assert.match(responsive,/user-role-badge\.privileged/);assert.match(platformCss,/platform-controls button\.primary/);assert.match(api,/mfa_policy==="staff_required"/);assert.match(api,/privileged:item\.role_key!=="user"/);});
test("uses layered light modals and keeps role assignment in user administration",async()=>{const[theme,platform,platformCss,adminCss]=await Promise.all([readFile(new URL("../app/theme.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/platform-controls.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/platform-controls.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-directory.css",import.meta.url),"utf8")]);assert.match(theme,/Light modals use layered sage surfaces/);assert.match(theme,/\.preferences-form/);assert.match(theme,/\.detail-actions/);assert.match(platform,/role-definition-grid/);assert.equal(platform.includes("saveAccess"),false);assert.equal(platform.includes("access-form"),false);assert.equal(platform.includes("Update access"),false);assert.match(platformCss,/\.role-definition-grid/);assert.match(adminCss,/\.admin-detail>\.primary/);});
test("guards account suspension and provides authorized audited unlocks",async()=>{const[api,admin,css,migration]=await Promise.all([readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/admin-directory.css",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_account_suspension_safety.sql",import.meta.url),"utf8")]);assert.match(api,/You cannot suspend your own account/);assert.match(api,/final active super administrator cannot be suspended/);assert.match(api,/Suspension confirmation is required/);assert.match(api,/account_suspended/);assert.match(api,/revokeUserSessions/);assert.match(api,/users\.unlock/);assert.match(api,/ban_duration:"none"/);assert.equal(api.includes("input.suspended_until"),false);assert.match(admin,/AccountStatusDialog/);assert.match(admin,/I understand this user will be signed out/);assert.match(admin,/Current account/);assert.match(css,/\.account-action-warning/);assert.match(migration,/support_admin','users\.unlock/);assert.match(migration,/suspension_reason/);});
test("ships private product feedback with safe diagnostics and staff workflow",async()=>{const[page,panel,admin,adminPanel,gallery,api,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/feedback-panel.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/admin/feedback-admin.tsx",import.meta.url),"utf8"),readFile(new URL("../app/private-feedback-gallery.tsx",import.meta.url),"utf8"),readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_product_feedback.sql",import.meta.url),"utf8")]);assert.match(page,/FeedbackPanel/);assert.match(page,/feedback-launcher-dot/);assert.match(panel,/Send feedback/);assert.match(panel,/feedback-unread-dot/);assert.match(panel,/Tokens, passwords, and protected coordinates are never included/);assert.match(panel,/safeScreenshot/);assert.match(admin,/feedback:"Feedback"/);assert.match(adminPanel,/Internal Note/);assert.match(adminPanel,/Duplicate Of/);assert.match(adminPanel,/AssociationPicker/);assert.match(adminPanel,/Send Response/);assert.equal(adminPanel.includes("GitHub issue URL"),false);assert.equal(adminPanel.includes("Passwords, tokens, query strings"),false);assert.match(gallery,/feedback-lightbox/);assert.match(gallery,/Zoom in/);assert.match(gallery,/const width=event\.currentTarget\.naturalWidth,height=event\.currentTarget\.naturalHeight;setDimensions/);assert.equal(gallery.includes("setDimensions(current=>({...current,[attachment.id]:`${event.currentTarget.naturalWidth}"),false);assert.ok(api.includes("/api/admin/feedback"));assert.ok(api.includes("feedback.create"));assert.ok(api.includes("/read"));assert.match(migration,/product_feedback_messages/);assert.match(migration,/feedback\.manage/);assert.match(migration,/feedback-attachments/);assert.match(migration,/key,description,sensitive/);});

test("creates a profile before recording a newly created account session",async()=>{const api=await readFile(new URL("../api/server.mjs",import.meta.url),"utf8");const setup=api.slice(api.indexOf("async function initializeSignup"),api.indexOf("const sessionTouches"));assert.ok(setup.indexOf("await ensureProfile(user)")<setup.indexOf("await rememberSession(req,result)"));assert.match(api,/Account setup failed\. Please try again\./);assert.match(api,/await initializeSignup\(req,result\)/);});

test("ships filtered high-contrast maps and banded bird reporting",async()=>{const[api,page,css,migration,seed]=await Promise.all([readFile(new URL("../api/server.mjs",import.meta.url),"utf8"),readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/queued-iteration.css",import.meta.url),"utf8"),readFile(new URL("../supabase/migrate_banded_birds_and_map_palette.sql",import.meta.url),"utf8"),readFile(new URL("../supabase/seed_bridge_to_20260804.sql",import.meta.url),"utf8")]);assert.match(api,/X-FeatherMap-Version/);assert.match(api,/\/api\/banded-birds/);assert.match(page,/category_breakdown\?\.\[filter\]/);assert.match(page,/species-selection-summary/);assert.match(page,/formatCountRange/);assert.match(css,/mix-blend-mode:normal/);assert.match(css,/taxonomy-actions/);assert.match(migration,/banded_bird_reports/);assert.match(seed,/2026-08-04/);});

test("uses friendly network errors, retryable photos, formatted counts, and canvas map activity",async()=>{const[page,errors,css,admin]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/request-errors.ts",import.meta.url),"utf8"),readFile(new URL("../app/queued-iteration.css",import.meta.url),"utf8"),readFile(new URL("../app/admin/page.tsx",import.meta.url),"utf8")]);assert.match(errors,/Bird activity could not be loaded/);assert.match(errors,/Your report was saved, but the photo could not be uploaded/);assert.match(page,/retryReportPhoto/);assert.match(page,/photoRetry/);assert.match(page,/ActivityCanvas/);assert.match(page,/toLocaleString\("en-US"\)/);assert.match(page,/map-moving/);assert.match(css,/\.activity-canvas/);assert.match(admin,/networkError\("admin"/);});
