"use client";
import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from "react";
import "./private-feedback-gallery.css";
const API=process.env.NEXT_PUBLIC_API_URL||"https://api.feather-map.com";
type Attachment={id:string;url:string;mime_type:string;byte_size:number;created_at:string};
export default function PrivateFeedbackGallery({attachments,token}:{attachments:Attachment[];token:string}){
 const[images,setImages]=useState<Record<string,string>>({}),[dimensions,setDimensions]=useState<Record<string,string>>({}),[active,setActive]=useState(-1),[zoom,setZoom]=useState(1),[offset,setOffset]=useState({x:0,y:0});const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 useEffect(()=>{let alive=true;const urls:string[]=[];Promise.all(attachments.map(async item=>{const response=await fetch(`${API}${item.url}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)return[item.id,""] as const;const url=URL.createObjectURL(await response.blob());urls.push(url);return[item.id,url] as const})).then(entries=>{if(alive)setImages(Object.fromEntries(entries))});return()=>{alive=false;urls.forEach(URL.revokeObjectURL)}},[attachments,token]);
 useEffect(()=>{if(active<0)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setActive(-1);if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[active,attachments.length]);
 function reset(){setZoom(1);setOffset({x:0,y:0})}function open(index:number){reset();setActive(index)}function move(delta:number){setActive(current=>(current+delta+attachments.length)%attachments.length);reset()}function pointerDown(event:ReactPointerEvent){if(zoom<=1)return;drag.current={x:event.clientX,y:event.clientY,ox:offset.x,oy:offset.y};event.currentTarget.setPointerCapture(event.pointerId)}function pointerMove(event:ReactPointerEvent){if(!drag.current)return;setOffset({x:drag.current.ox+event.clientX-drag.current.x,y:drag.current.oy+event.clientY-drag.current.y})}function pointerUp(){drag.current=null}
 const item=attachments[active],src=item&&images[item.id];
 return <><div className="private-feedback-gallery">{attachments.map((attachment,index)=><button key={attachment.id} onClick={()=>open(index)} aria-label={`Open screenshot ${index+1} full size`}>{images[attachment.id]?<img src={images[attachment.id]} alt={`Feedback screenshot ${index+1}`} onLoad={event=>setDimensions(current=>({...current,[attachment.id]:`${event.currentTarget.naturalWidth} × ${event.currentTarget.naturalHeight}`}))}/>:<span>Loading screenshot…</span>}</button>)}</div>{active>=0&&item&&<div className="feedback-lightbox" role="dialog" aria-modal="true" aria-label={`Screenshot ${active+1} of ${attachments.length}`} onClick={()=>setActive(-1)}><header onClick={event=>event.stopPropagation()}><div><b>Screenshot {active+1} of {attachments.length}</b><span>{item.mime_type.replace("image/","").toUpperCase()} · {dimensions[item.id]||"Loading dimensions"} · {Math.round(item.byte_size/1024)} KB · {new Date(item.created_at).toLocaleString()}</span></div><nav><button onClick={()=>setZoom(value=>Math.min(4,value+.25))} aria-label="Zoom in">+</button><button onClick={()=>setZoom(value=>Math.max(1,value-.25))} aria-label="Zoom out">−</button><button onClick={reset}>Fit</button><button onClick={()=>setActive(-1)} aria-label="Close image">×</button></nav></header><div className="feedback-lightbox-stage" onClick={event=>event.stopPropagation()} onWheel={event=>{event.preventDefault();setZoom(value=>Math.max(1,Math.min(4,value+(event.deltaY<0?.2:-.2))))}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}>{src?<img src={src} alt={`Full-size feedback screenshot ${active+1}`} style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`,cursor:zoom>1?"grab":"default"}}/>:<span>Loading full-size screenshot…</span>}</div>{attachments.length>1&&<><button className="feedback-lightbox-prev" onClick={event=>{event.stopPropagation();move(-1)}} aria-label="Previous screenshot">‹</button><button className="feedback-lightbox-next" onClick={event=>{event.stopPropagation();move(1)}} aria-label="Next screenshot">›</button></>}</div>}</>
}
