export type RequestOperation="activity"|"catalog"|"authentication"|"account"|"security"|"report"|"photo"|"comment"|"confirmation"|"delete-report"|"banded-bird"|"harvest"|"feedback"|"feedback-photo"|"admin"|"session"|"image";

const networkMessages:Record<RequestOperation,string>={
  activity:"Bird activity could not be loaded. Check your connection and try again.",catalog:"Bird and reporting options could not be loaded. Please try again.",authentication:"FeatherMap could not reach the sign-in service. Check your connection and try again.",account:"Your account changes could not be saved. Please try again.",security:"Security settings could not be updated. Your existing settings were not changed.",report:"Your report could not be submitted. It remains saved on this device.",photo:"Your report was saved, but the photo could not be uploaded.",comment:"Your comment could not be posted. Your text has been preserved.",confirmation:"Confirmation could not be saved. Please try again.","delete-report":"The report could not be deleted. No changes were made.","banded-bird":"The banded-bird report could not be saved.",harvest:"The harvest record could not be saved.",feedback:"Feedback could not be submitted. Your entry has been preserved.","feedback-photo":"Feedback was saved, but the screenshot could not be uploaded.",admin:"Administrative data could not be loaded. Check your connection and try again.",session:"Your session could not be refreshed because the connection was interrupted.",image:"This image is temporarily unavailable."
};

export function operationFor(path:string,method="GET"):RequestOperation{
  if(path.includes("/photos"))return"photo";if(path.includes("/comments"))return"comment";if(path.includes("/confirm"))return"confirmation";if(path.includes("/banded-birds"))return"banded-bird";if(path.includes("/harvests"))return"harvest";if(path.includes("/feedback")&&path.includes("attachments"))return"feedback-photo";if(path.includes("/feedback"))return"feedback";if(path.includes("/admin"))return"admin";if(path.includes("/auth/refresh"))return"session";if(path.includes("/auth/mfa")||path.includes("/auth/password"))return"security";if(path.includes("/auth/"))return"authentication";if(path.includes("/profile")||path.includes("/account"))return"account";if(path.includes("/catalog"))return"catalog";if(path.includes("/sightings")&&method==="DELETE")return"delete-report";if(path.includes("/sightings")&&method!=="GET")return"report";return"activity";
}

export function networkError(operation:RequestOperation,cause?:unknown){const error=new Error(networkMessages[operation]);if(cause!==undefined)(error as Error&{cause?:unknown}).cause=cause;return error}
